/**
 * WhatsApp bot: English & Swahili copy aligned with salon / saloon (TipTap).
 * Session fields stay legacy (restaurant_id, waiter_id, table_number) for API compatibility.
 */

const L = {
  en: {
    // Home
    home_welcome: 'Welcome to',
    home_choose: 'Choose an option:',
    home_type_zero: 'Type 0 anytime to return here.',
    home_main_services: 'MAIN MENU',
    serviceDesk: 'Services',
    services: 'Services',
    service_catalog_header: 'SERVICE CATALOG',
    section_search: 'SEARCH',
    section_categories: 'CATEGORIES',
    section_home: 'HOME',
    search_services_hint: 'Search services',
    // Menu items (service catalog + payments)
    menu_view: 'Browse services & products',
    menu_view_desc: 'Service menu image & bookings',
    rate_service: 'Rate',
    rate_desc: 'Feedback for your visit',
    pay_bill: 'Pay bill',
    pay_bill_desc: 'Pay your booking or send a payment',
    tip: 'Tip',
    tip_skip: 'Skip',
    tip_choose_amount: 'Choose a tip amount (Tsh):',
    tip_desc: 'Tip your stylist',
    call_waiter: 'Call stylist',
    call_waiter_desc: 'Ask for help or a receipt',
    guest_wifi: 'WiFi password',
    guest_wifi_desc: 'Guest network name & password',
    guest_wifi_title: 'Guest Wi‑Fi',
    guest_wifi_ssid_label: 'Network:',
    guest_wifi_password_label: 'Password:',
    guest_wifi_not_set: 'Wi‑Fi details are not set yet. Ask the receptionist.',
    guest_wifi_error: 'Could not load Wi‑Fi details. Try again later.',
    guest_wifi_no_session: 'Join the saloon chat first (scan QR or pick your saloon), then open WiFi password again.',
    change_language: 'Change language',
    change_language_desc: 'English / Kiswahili',
    exit: 'Exit',
    exit_desc: 'Leave the chat',
    // Language selection
    select_language: 'Choose language:',
    lang_english: 'English',
    lang_swahili: 'Kiswahili',
    language_changed: 'Language set to English.',
    language_changed_sw: 'Lugha imewekwa kwa Kiswahili.',
    // Menu image
    downloading_menu: 'Loading service menu image…',
    here_is_menu: 'Here is our service & retail menu!',
    menu_type_order: 'Type your booking (e.g. treatment name & qty) or type 0 to go back.',
    menu_commands: 'Shortcuts:',
    menu_cmd_zero: '0 = Back to main menu',
    menu_cmd_order: 'Booking = type service/product and quantity (e.g. Oil 1, Treatment 2)',
    home_btn: 'Home (0)',
    menu_not_available: 'Sorry, no service menu image yet. Type 0 to go back.',
    // Pay bill / phone
    enter_phone_billed: 'Enter the phone number to bill (e.g. 0712345678):',
    enter_phone_tip: 'Enter phone number for the tip (e.g. 0712345678):',
    enter_phone_pay: 'Enter phone number to pay (e.g. 0712345678):',
    enter_amount: 'Enter amount (Tsh):',
    tip_amount: 'Tip amount for',
    invalid_number: 'Invalid number. Try again.',
    invalid_amount: 'Invalid amount. Use numbers only.',
    sending_request: 'Sending payment request…',
    request_sent: 'Request sent to',
    confirm_on_phone: 'Please confirm on your phone.',
    bot_confirm_auto: 'TipTap will confirm automatically when payment is received.',
    // Customer support
    support_title: 'Client support',
    support_call: 'Call or WhatsApp:',
    support_type_zero: 'Type 0 to return to the main menu.',
    back_to_menu: 'Back to menu',
    choose: 'Choose:',
    // General
    table: 'Seat',
    goodbye: 'Goodbye — thank you for visiting our saloon.',
    processing_order: 'Processing your booking…',
    order_received: 'Booking received!',
    confirm_booking_title: 'Confirm booking',
    cash_pay_instructions: 'Pay at the saloon (cash to stylist), then tap the button below.',
    cash_paid_btn: 'I HAVE PAID',
    order_id: 'Booking #',
    items_found: 'Lines added:',
    total: 'Total:',
    waiter_confirm: 'Your stylist will confirm shortly…',
    pay_now: 'Pay now',
    track_status: 'Track status',
    home: 'Home',
    error_try_again: 'Something went wrong. Please try again.',
    error_order: 'We could not match your text to the service catalog.',
    try_clear: 'Try typing clearly (e.g. "Oil 2, Treatment 1"). Type 0 to go back.',
    verifying: 'Verifying…',
    invalid_qr: 'Invalid code or QR.',
    enter_table: 'Enter your seat name or number (e.g. 3 or Station A):',
    valid_table: 'Please enter a valid seat.',
    order_which_table: 'Which seat are you on?',
    order_reply_table_number: 'Reply with the seat name or number (e.g. 1, 2, 3).',
    thanks_feedback: 'Thank you for your feedback!',
    thanks_using_tiptap: 'Thanks for using TipTap!\n\nWe hope to see you again.',
    comment_prompt: 'Add a short comment, or type END to skip.',
    not_understood: 'Sorry, I did not understand. Type Hi to start again.',
    // Stylist offline & call flow
    waiter_offline_msg:
      '*{name}* is currently *offline*.\n\nYou can:\n• Type *0* — Main menu\n• Type *EXIT* — Leave\n• Scan another stylist QR — for someone who is online',
    call_waiter_sent: 'Your request (*{label}*) was sent. A stylist will attend shortly.',
    call_waiter_failed: 'Could not send the request. Please try again later.',
    call_waiter_table_invalid: 'Enter a valid seat (e.g. 1, 2, 5) or pick from the list.',
    waiters_list_title: 'Stylists on duty',
    waiters_list_subtitle: 'Choose a stylist to call (online stylists receive requests).',
    waiters_list_empty: 'No stylists are listed right now.',
    waiters_list_btn: 'View stylists',
    waiters_offline_badge: '(Offline)',
    waiters_tap_to_call: 'Tap to request',
    waiters_not_on_duty: 'Not on duty',
    // Extra (handler hardcoded → T())
    tech_error: 'Technical error. Please try again.',
    stylist_cmd_reply: 'You are with stylist *{name}* (active).',
    stylist_cmd_none: 'You are not linked to a stylist yet. Scan a stylist or seat QR, or search for a saloon.',
    status_need_context: 'Scan a seat or stylist QR, or search for a saloon first — then you can track your booking.',
    welcome_tiptap:
      '👋 Welcome to TipTap!\nScan your stylist or seat QR, or search for a saloon by name.',
    search_type_saloon: 'Type the saloon name:',
    found_saloons: 'Saloons found:',
    choose_number_hint: 'Reply with the number:',
    pick_seat_title: 'Choose your seat',
    pick_seat_line: 'Seat {name} · up to {cap} clients',
    pick_seat_free: 'Or type your seat number (e.g. 7):',
    cmd_stylist: '!stylist',
    cmd_stylist_legacy: '!waiter',
    invalid_entry_help:
      'No match.\n\n• *TipTap stylist ID*: 4 digits (e.g. 0042) or older TIPTAP-W-12345 (your account; works after you are linked to a saloon)\n• *At the saloon*: ABC-T01 = seat, ABC-W01 = stylist at that saloon (ABC = that saloon’s prefix)\n• *WhatsApp QR text*: START_5_S12 = saloon 5 + stylist user 12 (S = stylist; old QRs may show …_W12 — still works)\n\nOr scan the official QR / type the saloon name to search.',
    bill_payment_desc: 'Bill payment',
    call_stylist_label: 'Call stylist',
    request_bill_label: 'Request bill',
    call_options_prompt: '🙋 *What do you need?*',
    stylists_list_btn: 'Stylist list',
    order_cancelled: 'Booking cancelled.',
    cart_cleared: 'Cart cleared.',
    cash_thanks: 'Thank you!\n\nWaiting for your stylist to confirm cash…',
    invalid_phone_format: 'Invalid number. Use 0712345678 or 255712345678',
    txn_id_prompt: 'Enter transaction ID (e.g. MPESA123XYZ):',
    txn_received: 'Reference received.\nWaiting for confirmation…',
    track_fetch_error: 'Could not load booking status.',
    no_active_booking_seat: 'No active booking for this seat.',
    no_booking_pay: 'No active booking to pay.',
    bill_header: 'Your bill',
    payment_order_label: 'Booking',
    booking_status_label: 'Booking status',
    payment_label: 'Payment',
    payment_status_line: 'Booking: {s}\nPayment: {p}\n\nStill waiting for payment…',
    feedback_prompt_title: 'Feedback',
    feedback_prompt_body: 'What would you like to rate?',
    feedback_saloon: 'Saloon experience',
    feedback_stylist: 'Stylist service',
    feedback_pick_stylist: 'Choose a stylist to rate:',
    feedback_pick_stylist_sw: 'Chagua stylist kwa rating:',
    feedback_no_stylists: 'No stylists to show right now.',
    feedback_no_stylists_sw: 'Hakuna stylist kwa sasa.',
    feedback_rate_title: 'Rate',
    feedback_stars_prompt: 'Tap a star rating:',
    tip_no_booking: 'You need an active booking before tipping from this screen.',
    tip_thanks_amount: 'Thanks for the Tsh {amount} tip!',
    tip_error: 'Could not send the tip. Try again.',
    search_not_found: 'Not found. Try another name.',
    search_error: 'Search error. Try again.',
    menu_pick_title: 'How do you want to browse?',
    menu_pick_image: 'Service menu (image)',
    menu_pick_list: 'List by category',
    categories_select: 'Choose a category',
    categories_view: 'Categories',
    menu_unavailable: 'Service list is unavailable right now.',
    menu_fetch_error: 'Could not load the service list. Try again later.',
    items_none: 'Nothing listed here.',
    item_not_found: 'Item not found.',
    categories_empty_suffix: 'items',
    order_received_generic: 'Booking received! Your stylist will follow up.',
    list_menu_fallback_error: 'Technical error. Try the service menu image or type 0.',
    saloon_fallback_name: 'Saloon',
    restaurant_fallback_name: 'Saloon',
    choose_next: 'What would you like next?',
    payment_confirmed_thanks: 'Payment confirmed — thank you!',
    track_booking: 'Track booking',
    rate_service_btn: 'Rate visit',
    status_icons_pending: 'Queued',
    status_icons_confirmed: 'Confirmed',
    status_icons_preparing: 'In progress',
    status_icons_ready: 'Ready',
    status_icons_served: 'Done',
    status_icons_paid: 'Paid',
    status_payment_paid: 'Paid',
    status_payment_pending: 'Pending',
    stylist_label: 'Stylist',
    tip_for_stylist: 'Tip for {name}',
    tip_pick_stylist: 'Choose a stylist for your tip:',
    tip_pick_stylist_sw: 'Chagua stylist wa kumpa tip:',
    tip_row_desc: 'Send tip',
    tip_row_desc_sw: 'Mpe tip',
    chagua: 'Choose:',
    check_tena: 'Check again',
    quick_pay_issue: 'Something went wrong with payment. Please try again later.',
    payment_confirmed_poll: 'Payment confirmed — thank you!',
    payment_status_title: 'Status update',
    payment_waiting_sw: 'Still waiting for payment…',
    ussd_error: 'USSD error',
    try_again: 'Try again',
    cash_option: 'Cash',
    manual_ussd_title: 'Manual USSD',
    manual_ussd_dial: 'Dial *150*00# (or your network code)',
    manual_ussd_amount: 'Amount',
    manual_ussd_when_done: 'When done, tap:',
    feedback_go_rate: 'Rate visit',
    service_lines: 'Your services & products:',
    refresh_btn: 'Refresh',
    cart_title: 'Your cart',
    cart_empty_title: 'Cart is empty',
    added_title: 'Added',
    continue_shopping: 'Add more',
    go_cart: 'Go to cart',
    edit_cart_title: 'Edit cart',
    view_lines: 'Lines',
    feedback_rating_for: 'Rating for {name}',
    feedback_stars_intro: 'How many stars?',
    feedback_row_hint: 'Tap to rate',
  },
  sw: {
    home_welcome: 'Karibu',
    home_choose: 'Chagua:',
    home_type_zero: 'Andika 0 wakati wowote kurudi hapa.',
    home_main_services: 'MENYU KUU',
    serviceDesk: 'Huduma',
    services: 'Huduma',
    service_catalog_header: 'ORODHA YA HUDUMA',
    section_search: 'TAFUTA',
    section_categories: 'MAKUNDI',
    section_home: 'NYUMBANI',
    search_services_hint: 'Tafuta huduma',
    menu_view: 'Huduma na bidhaa',
    menu_view_desc: 'Picha ya menyu na maagizo',
    rate_service: 'Kadiria',
    rate_desc: 'Maoni ya ziara',
    pay_bill: 'Lipa bili',
    pay_bill_desc: 'Lipa booking au tuma malipo',
    tip: 'Tip / mchango',
    tip_skip: 'Ruka',
    tip_choose_amount: 'Chagua kiasi cha tip (Tsh):',
    tip_desc: 'Mchango kwa stylist',
    call_waiter: 'Mwita stylist',
    call_waiter_desc: 'Msaada au ombi la risiti',
    guest_wifi: 'Nenosiri la WiFi',
    guest_wifi_desc: 'Jina la mtandao na nenosiri',
    guest_wifi_title: 'WiFi ya wageni',
    guest_wifi_ssid_label: 'Mtandao:',
    guest_wifi_password_label: 'Nenosiri:',
    guest_wifi_not_set: 'Maelezo ya WiFi hayajawekwa. Uliza mapokezi.',
    guest_wifi_error: 'Hatukuweza kupakia WiFi. Jaribu tena baadaye.',
    guest_wifi_no_session: 'Anza kwanza (skeni QR au chagua saloon), kisha fungua nenosiri la WiFi tena.',
    change_language: 'Badilisha lugha',
    change_language_desc: 'English / Kiswahili',
    exit: 'Toka',
    exit_desc: 'Acha mazungumzo',
    select_language: 'Chagua lugha:',
    lang_english: 'English',
    lang_swahili: 'Kiswahili',
    language_changed: 'Language set to English.',
    language_changed_sw: 'Lugha imewekwa kwa Kiswahili.',
    downloading_menu: 'Inapakia picha ya menyu ya huduma…',
    here_is_menu: 'Hii ni menyu ya huduma na bidhaa!',
    menu_type_order: 'Andika booking (mf. jina la huduma + idadi) au 0 kurudi.',
    menu_commands: 'Majarida:',
    menu_cmd_zero: '0 = Rudi kwenye menyu kuu',
    menu_cmd_order: 'Booking = andika huduma/bidhaa na idadi (mf. Oil 1, Treatment 2)',
    home_btn: 'Nyumbani (0)',
    menu_not_available: 'Samahani, picha ya menyu haipo. Andika 0 kurudi.',
    enter_phone_billed: 'Ingiza nambari ya simu ya kulipiwa (mf. 0712345678):',
    enter_phone_tip: 'Ingiza nambari ya simu ya tip (mf. 0712345678):',
    enter_phone_pay: 'Ingiza nambari ya simu ya kulipa (mf. 0712345678):',
    enter_amount: 'Ingiza kiasi (Tsh):',
    tip_amount: 'Kiasi cha tip kwa',
    invalid_number: 'Nambari si sahihi. Jaribu tena.',
    invalid_amount: 'Kiasi si sahihi. Tumia nambari tu.',
    sending_request: 'Inatumia ombi la malipo…',
    request_sent: 'Ombi limetumwa kwa',
    confirm_on_phone: 'Tafadhali thibitisha kwenye simu yako.',
    bot_confirm_auto: 'TipTap itathibitisha moja kwa moja malipo yanapopokelewa.',
    support_title: 'Msaada kwa wateja',
    support_call: 'Piga au WhatsApp:',
    support_type_zero: 'Andika 0 kurudi kwenye menyu kuu.',
    back_to_menu: 'Rudi menyu',
    choose: 'Chagua:',
    table: 'Kiti / kituo',
    goodbye: 'Kwaheri — asante kwa kutembelea saloon yetu.',
    processing_order: 'Inachakata booking…',
    order_received: 'Booking imepokelewa!',
    confirm_booking_title: 'Thibitisha booking',
    cash_pay_instructions: 'Lipa saloon (kwa stylist), kisha bonyeza kitufe hapa chini.',
    cash_paid_btn: 'NIMELIPA',
    order_id: 'Booking #',
    items_found: 'Vitu vilivyongezwa:',
    total: 'Jumla:',
    waiter_confirm: 'Stylist atathibitisha hivi karibuni…',
    pay_now: 'Lipa sasa',
    track_status: 'Fuatilia hali',
    home: 'Nyumbani',
    error_try_again: 'Kuna tatizo la kiufundi. Jaribu tena.',
    error_order: 'Hatukuweza kupatanisha na orodha ya huduma.',
    try_clear: 'Andika wazi (mf. "Oil 2, Treatment 1"). Andika 0 kurudi.',
    verifying: 'Inathibitisha…',
    invalid_qr: 'Msimbo au QR si sahihi.',
    enter_table: 'Ingiza jina au nambari ya kiti (mf. 3 au Station A):',
    valid_table: 'Tafadhali ingiza kiti halali.',
    order_which_table: 'Upo kiti / kituo gani?',
    order_reply_table_number: 'Jibu kwa jina au nambari ya kiti (mf. 1, 2, 3).',
    thanks_feedback: 'Asante kwa maoni yako!',
    thanks_using_tiptap: 'Asante kwa kutumia TipTap!\n\nKaribu tena.',
    comment_prompt: 'Andika maoni mafupi, au END bila maoni.',
    not_understood: 'Samahani, sikuweza kuelewa. Andika Hi kuanza.',
    waiter_offline_msg:
      '*{name}* sasa *haiko online*.\n\nUnaweza:\n• Andika *0* — Menyu kuu\n• Andika *EXIT* — Toka\n• Scan QR ya stylist mwingine — aliye online',
    call_waiter_sent: 'Ombi (*{label}*) limetumwa. Stylist atakuja hivi karibuni.',
    call_waiter_failed: 'Kutuma ombi kumeshindikana. Jaribu tena baadaye.',
    call_waiter_table_invalid: 'Ingiza kiti halali (mf. 1, 2, 5) au chagua orodha.',
    waiters_list_title: 'Stylist waliopo',
    waiters_list_subtitle: 'Chagua stylist (walioko online wanapokea ombi).',
    waiters_list_empty: 'Hakuna stylist kwenye orodha sasa hivi.',
    waiters_list_btn: 'Orodha ya stylist',
    waiters_offline_badge: '(Haiko online)',
    waiters_tap_to_call: 'Gusa kuomba',
    waiters_not_on_duty: 'Haiko kazini',
    tech_error: 'Hitilafu ya kiufundi. Jaribu tena.',
    stylist_cmd_reply: 'Unahudumiwa na stylist *{name}* (hai).',
    stylist_cmd_none: 'Bado huna stylist. Scan QR ya stylist au kiti, au tafuta saloon kwa jina.',
    status_need_context: 'Scan QR ya kiti au stylist, au tafuta saloon kwanza — kisha utaweza fuatilia booking.',
    welcome_tiptap:
      '👋 Karibu TipTap!\nScan QR ya stylist au kiti, au tafuta saloon kwa jina.',
    search_type_saloon: 'Andika jina la saloon:',
    found_saloons: 'Saloon zilizopatikana:',
    choose_number_hint: 'Jibu kwa nambari:',
    pick_seat_title: 'Chagua kiti chako',
    pick_seat_line: 'Kiti {name} · hadi wateja {cap}',
    pick_seat_free: 'Au andika nambari ya kiti (mf. 7):',
    cmd_stylist: '!stylist',
    cmd_stylist_legacy: '!waiter',
    invalid_entry_help:
      'Hakuna mechi.\n\n• *Kitambulisho cha TipTap*: msimbo wa herufi/namba (mf. 09E26870), nambari 4 za zamani, au TIPTAP-W-12345 (akaunti yako; inafanya ukiunganishwa na saloon)\n• *Ndani ya saloon*: ABC-T01 = kiti, ABC-W01 = stylist wa saloon hiyo (ABC = kifupi cha saloon)\n• *QR ya WhatsApp*: START_5_S12 = saloon 5 + stylist 12 (S = stylist; QR za zamani zinaweza kuwa …_W12 — bado zinafanya kazi)\n\nAu scan QR rasmi / andika jina la saloon kutafuta.',
    bill_payment_desc: 'Malipo ya bili',
    call_stylist_label: 'Mwita stylist',
    request_bill_label: 'Omba bili',
    call_options_prompt: '🙋 *Unahitaji nini?*',
    stylists_list_btn: 'Orodha ya stylist',
    order_cancelled: 'Booking imefutwa.',
    cart_cleared: 'Kikapu kimefutwa.',
    cash_thanks: 'Asante!\n\nTunasubiri stylist athibitishe pesa taslimu…',
    invalid_phone_format: 'Nambari si sahihi. Tumia 0712345678 au 255712345678',
    txn_id_prompt: 'Ingiza kitambulisho cha muamala (mf. MPESA123XYZ):',
    txn_received: 'Kitambulisho kimepokelewa.\nTunasubiri uthibitisho…',
    track_fetch_error: 'Imeshindwa kupakia hali ya booking.',
    no_active_booking_seat: 'Hakuna booking hai kwa kiti hiki.',
    no_booking_pay: 'Hakuna booking ya kulipa.',
    bill_header: 'Bili yako',
    payment_order_label: 'Booking',
    booking_status_label: 'Hali ya booking',
    payment_label: 'Malipo',
    payment_status_line: 'Booking: {s}\nMalipo: {p}\n\nBado tunasubiri malipo…',
    feedback_prompt_title: 'Maoni',
    feedback_prompt_body: 'Ungependa kukadiria nini?',
    feedback_saloon: 'Uzoefu wa saloon',
    feedback_stylist: 'Huduma ya stylist',
    feedback_pick_stylist: 'Chagua stylist kwa rating:',
    feedback_pick_stylist_sw: 'Chagua stylist kwa rating:',
    feedback_no_stylists: 'Hakuna stylist kwa sasa.',
    feedback_no_stylists_sw: 'Hakuna stylist kwa sasa.',
    feedback_rate_title: 'Kadiria',
    feedback_stars_prompt: 'Chagua nyota:',
    tip_no_booking: 'Unahitaji booking hai kabla ya tip kutoka skrini hii.',
    tip_thanks_amount: 'Asante kwa tip ya Tsh {amount}!',
    tip_error: 'Kutuma tip kumeshindikana. Jaribu tena.',
    search_not_found: 'Haikupatikana. Jaribu jina lingine.',
    search_error: 'Hitilafu ya utafutaji. Jaribu tena.',
    menu_pick_title: 'Ungependa kutazama vipi?',
    menu_pick_image: 'Menyu (picha)',
    menu_pick_list: 'Orodha kwa jamii',
    categories_select: 'Chagua jamii',
    categories_view: 'Makundi',
    menu_unavailable: 'Orodha ya huduma haipatikani kwa sasa.',
    menu_fetch_error: 'Imeshindwa kupakia huduma. Jaribu tena baadaye.',
    items_none: 'Hakuna vitu hapa.',
    item_not_found: 'Kipengele hakipo.',
    categories_empty_suffix: 'vitu',
    order_received_generic: 'Booking imepokelewa! Stylist atafuatilia.',
    list_menu_fallback_error: 'Hitilafu ya kiufundi. Jaribu menyu ya picha au andika 0.',
    saloon_fallback_name: 'Saloon',
    restaurant_fallback_name: 'Saloon',
    choose_next: 'Ungependa nini baada ya hapo?',
    payment_confirmed_thanks: 'Malipo yamethibitishwa — asante!',
    track_booking: 'Fuatilia booking',
    rate_service_btn: 'Kadiria ziara',
    status_icons_pending: 'Inasubiri',
    status_icons_confirmed: 'Imethibitishwa',
    status_icons_preparing: 'Inaendelea',
    status_icons_ready: 'Tayari',
    status_icons_served: 'Imekamilika',
    status_icons_paid: 'Imelipwa',
    status_payment_paid: 'Imelipwa',
    status_payment_pending: 'Inasubiri',
    stylist_label: 'Stylist',
    tip_for_stylist: 'Tip kwa {name}',
    tip_pick_stylist: 'Chagua stylist wa kumpa tip:',
    tip_pick_stylist_sw: 'Chagua stylist wa kumpa tip:',
    tip_row_desc: 'Tuma tip',
    tip_row_desc_sw: 'Mpe tip',
    chagua: 'Chagua:',
    check_tena: 'Angalia tena',
    quick_pay_issue: 'Kuna tatizo la malipo. Jaribu tena baadaye.',
    payment_confirmed_poll: 'Malipo yamethibitishwa — asante!',
    payment_status_title: 'Hali ya malipo',
    payment_waiting_sw: 'Bado tunasubiri malipo…',
    ussd_error: 'Hitilafu USSD',
    try_again: 'Jaribu tena',
    cash_option: 'Taslimu',
    manual_ussd_title: 'USSD ya mkono',
    manual_ussd_dial: 'Piga *150*00# (au nambari ya mtandao wako)',
    manual_ussd_amount: 'Kiasi',
    manual_ussd_when_done: 'Ukimaliza, gusa:',
    feedback_go_rate: 'Kadiria ziara',
    service_lines: 'Huduma / bidhaa:',
    refresh_btn: 'Sasisha',
    cart_title: 'Kikapu chako',
    cart_empty_title: 'Kikapu tupu',
    added_title: 'Imeongezwa',
    continue_shopping: 'Ongeza zaidi',
    go_cart: 'Enda kikapuni',
    edit_cart_title: 'Hariri kikapu',
    view_lines: 'Vitu',
    feedback_rating_for: 'Rating kwa {name}',
    feedback_stars_intro: 'Nyota ngapi?',
    feedback_row_hint: 'Gusa kukadiria',
  },
};

function T(session, key) {
  const lang = session.lang || 'en';
  const s = L[lang] && L[lang][key];
  return s !== undefined ? s : (L.en[key] || key);
}

/** Replace {name}, {amount}, etc. in a translated string. */
function TRepl(session, key, vars = {}) {
  let s = T(session, key);
  Object.entries(vars).forEach(([k, v]) => {
    s = s.split(`{${k}}`).join(String(v));
  });
  return s;
}

module.exports = { L, T, TRepl };
